version: '3.6'

services:
  migrate:
    image: boxfuse/flyway:5.0
    volumes:
      - ./database/sql:/flyway/sql
      - ./database/test:/flyway/sql/test
    command: migrate
    environment:
      - FLYWAY_URL=jdbc:postgresql://dld-database/${DATABASE_NAME}
      - FLYWAY_USER=${DATABASE_USER}
      - FLYWAY_PASSWORD=${DATABASE_PASSWORD}
      - FLYWAY_SCHEMAS=public
  dld-database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5434:5432
  web:
    image: ocampor/go-api
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - POSTGRES_URI=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@dld-database/${DATABASE_NAME}?sslmode=disable
