version: '3.6'

services:
  dld-database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
    ports:
      - 5434:5432
  web:
    image: ocampor/go-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:8000
    environment:
      - POSTGRES_URI=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@dld-database/${DATABASE_NAME}?sslmode=disable
